apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blah-deploy
  name: blah-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blah-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blah-deploy
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
        resources: {}
status: {}
